# Generated by Django 3.2.4 on 2021-06-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.categoria')),
            ],
        ),
    ]
