# Generated by Django 3.2.4 on 2021-06-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210629_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='encabezado',
            field=models.CharField(default=1, max_length=100, verbose_name='Encabezado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Contenido'),
        ),
    ]
