# Generated by Django 3.2.4 on 2021-07-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
